In [31]:
import torch
import wandb
import hydra
from tqdm import tqdm
import torchvision
from hydra.utils import instantiate
import os
from torch.utils.data import Dataset, DataLoader
from PIL import Image
import pandas as pd
import torch

In [34]:
from cutout import Cutout
cut = Cutout(1, 3)
imgs = torch.Tensor(2,3,10,10)
cut(imgs)

ImportError: cannot import name 'Cutout' from 'cutout' (/Users/caffin/Desktop/INF473V/gitforinf473/baselinemodified/cutout.py)

In [30]:
permutation = torch.randperm(10)
indexs = permutation[0:20]
permutation, indexs

(tensor([9, 4, 7, 0, 8, 3, 5, 6, 2, 1]),
 tensor([9, 4, 7, 0, 8, 3, 5, 6, 2, 1]))

In [ ]:
from torchvision.transforms import transforms
from RandAugment import RandAugment

transform_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
    std=[0.229, 0.224, 0.225]),
])

# Add RandAugment with N, M(hyperparameter)
transform_train.transforms.insert(0, RandAugment(4, 5))

In [28]:
test = torch.tensor([1,3,4,2,5,7,3])
(test>1)

tensor([False,  True,  True,  True,  True,  True,  True])

In [ ]:
torchvision.transforms.ToTensor()

In [23]:
class unlabelledDataset(Dataset):
    def __init__(self, test_dataset_path):
        self.test_dataset_path = test_dataset_path
        images_list = os.listdir(self.test_dataset_path)
        # filter out non-image files
        self.images_list = [image for image in images_list if image.endswith(".jpg")]
        # set a non exist label
        self.labels = [48] * len(self.images_list)
        self.labels = torch.tensor(self.labels).type(torch.LongTensor)

    def __getitem__(self, idx):
        image_name = self.images_list[idx]
        label = self.labels[idx]
        image_path = os.path.join(self.test_dataset_path, image_name)
        image = Image.open(image_path)
        return image, label, idx

    def __len__(self):
        return len(self.images_list)
    
    def set_label(self, newlabel, idx):
         self.labels[idx] = newlabel
dataload = unlabelledDataset('dataset/unlabelled/')
for i in dataload:
    name = i[2]
    image = i[0]
    if name<200000:
        image.save(f'dataset/200/{name}.jpg')
    else :
        break

In [20]:
dataload = unlabelledDataset('dataset/unlabelled/')

In [17]:
print(len(dataload))

296874


In [21]:
for i in dataload:
    name = i[2]
    image = i[0]
    if name<100000:
        image.save(f'dataset/001/{name}.jpg')
    elif name<200000:
        image.save(f'dataset/002/{name}.jpg')
    else :
        break

In [16]:
for i in DataLoader(dataload,batch_size=1,):
    name = i[2]
    image = torchvision.transforms.ToPILImage()(i[0].squeeze())
    image.save(f'dataset/unlabelled_selected/{name}.jpg')
    #torchvision.io.write_file(image_tensor, 'dataset/unlabelled_selected/')

In [2]:
torchvision.transforms.RandomRotation()

TypeError: __init__() missing 1 required positional argument: 'degrees'

In [12]:
torchvision.transforms.ColorJitter()

ColorJitter(brightness=None, contrast=None, saturation=None, hue=None)

In [8]:
dataset = torchvision.datasets.ImageFolder('dataset/train',transform=
                                           torchvision.transforms.Compose([
                                               torchvision.transforms.Resize([224,224]),
                                               torchvision.transforms.ToTensor,
                                               torchvision.transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                                                                std=[0.229, 0.224, 0.225]),
                                           ]))

In [3]:
train_dataset, val_dataset = torch.utils.data.random_split(
            dataset,
            [
                int(0.8 * len(dataset)),
                len(dataset) - int(0.8 * len(dataset)),
            ],
            generator=torch.Generator().manual_seed(3407),
        )

In [4]:
aug1 = torchvision.transforms.Compose([
    torchvision.transforms.RandomHorizontalFlip(),
    torchvision.transforms.GaussianBlur(kernel_size=7),
    torchvision.transforms.GaussianBlur(kernel_size=9),
    torchvision.transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                    std=[0.229, 0.224, 0.225]),
])

In [9]:
load1 = torch.utils.data.DataLoader(dataset,batch_size=10,shuffle=True,num_workers=8)

In [10]:
load1

In [31]:
testset = torch.Tensor([[1,2],[1,2]])
list=[]
list.append(testset)
list.append(testset)
torch.Tensor(list)

ValueError: only one element tensors can be converted to Python scalars

In [34]:
list = [[1,3,4,5,6],[1,3,4,2,4]]
torch.tensor(list).tolist()

[[1, 3, 4, 5, 6], [1, 3, 4, 2, 4]]

In [36]:
test = torch.Tensor([1,3,5,2,1,4,8])
test.argmax()

tensor(6)